### ISSUE TITLE
Why this library needs the expo dependencies?

### ISSUE THREAD

**Issue by danielang** [wcandillon/react-native-responsive-ui#10]

**Comment by wcandillon** [comment]
@danielang good point 👍

**Comment by chapeljuice** [comment]
Looks like this is still an issue. Any progress?

**Comment by btrane** [comment]
If you're not using Expo, open up the .babelrc (in `node_modules/react-native-responsive-ui`) and change the presets to `react-native`:

```
{
    "presets": [
        "react-native"
    ],
    "env": {
        "development": {
            "plugins": [
                "transform-react-jsx-source"
            ]
        }
    }
}
```

**Comment by wcandillon** [comment]
This is fixed now. However this new version is non backward compatible.
