### ISSUE TITLE
Failed to build DependencyGraph: @providesModule naming collision

### ISSUE THREAD

**Issue by mleduque** [wcandillon/react-native-responsive-ui#16]
Hi,
After adding this dependency, I get:
Bundling `index.android.js`
  Analysing...Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: <path>/node_modules/react-native-responsive-ui/node_modules/react-native/package.json collides with<path>/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: <path>/node_modules/react-native-responsive-ui/node_modules/react-native/package.json collides with <path>/node_modules/react-native/package.json

I don't really know what this means, and googling for that made me more confused than expected.
I don't know if that's relevant, I'm using react-native 0.42 (0.43+ only cause dependency conflicts because modules won't use an alpha version of react).

**Comment by schneck** [comment]
Same here, using react-native 0.44.2

**Comment by dniccum** [comment]
I am seeing this in react-native 0.47.1

**Comment by GianniGM** [comment]
Same issue using react-native 0.48.1.

**Comment by gregblass** [comment]
Also getting this using 0.44. Looks like there is a version of react-native included with this library for some reason? What's the deal with that?

**Comment by wcandillon** [comment]
Sorry for being so late in pushing the fix for it. It should be published today: https://github.com/wcandillon/react-native-responsive-ui/pull/18
