### ISSUE TITLE
TransformError: Couldn't find preset "babel-preset-expo" relative to directory

### ISSUE THREAD

**Issue by kayluhb** [wcandillon/react-native-responsive-ui#25]
Getting an error when running for the first time in a new project. 

```sh
bundling failed: "TransformError: /Users/kayluhb/Projects/TestProject/node_modules/react-native-responsive-ui/lib/index.js: Couldn't find preset \"babel-preset-expo\" relative to directory \"/Users/kayluhb/Projects/TestProject/node_modules/react-native-responsive-ui\""
```

Looks like it's looking for the babel-preset-expo.

```json
"dependencies": {
    "react": "16.0.0",
    "react-native": "0.48.4",
    "react-native-responsive-ui": "^1.1.1"
  },
```

**Comment by jaulz** [comment]
The same for me... any workaround?

**Comment by kayluhb** [comment]
@jaulz I just installed it :(  `yarn add babel-preset-expo --dev`. I'm not using it, but it's there.

**Comment by chapeljuice** [comment]
@kayluhb that didn't work for me ... any other thoughts? I'm still getting the TransformError
```
Couldn't find preset \"babel-preset-expo\"
```

**Comment by alanyong91** [comment]
Just `npm i babel-preset-expo` will fix this problem

**Comment by agenthunt** [comment]
But, do we need this external dependency ?  I cant see it being used anywhere other than that the project has been setup with an expo project.  Can the project be restructured as a   pure js library ?

**Comment by kayluhb** [comment]
@agenthunt I don't think it should be a dependency IMHO.

**Comment by tatsna** [comment]
@kayluhb Is work!

**Comment by geminiyellow** [comment]
add the preset can fix the error, but , we dont need it, why we should add it?

just merge this [Remove expo babel preset #34](https://github.com/wcandillon/react-native-responsive-ui/pull/34)

**Comment by kayluhb** [comment]
👍 thanks @geminiyellow
