### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by piranna** [wcandillon/react-native-responsive-ui#27]
I'm using React 16 but get the error `npm WARN react-native-responsive-ui@1.1.1 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself`

**Comment by piranna** [comment]
The same happens with React Native, `npm WARN react-native-responsive-ui@1.1.1 requires a peer of react-native@^0.43.4 but none is installed. You must install peer dependencies yourself`. Current latest with support for React 16 is 0.50.0-rc.1

**Comment by jaulz** [comment]
Any news on this?

**Comment by wcandillon** [comment]
This is fixed now. However this new version is non backward compatible.
