### ISSUE TITLE
Can you use the library with vanilla JS i.e. without flow?

### ISSUE THREAD

**Issue by tanx** [wcandillon/react-native-responsive-ui#36]
Hey. thanks for your cool library. Is it possible to use the lib without flow? I'm getting this error when installing via npm:

```
ERROR in ./node_modules/react-native-responsive-ui/lib/MediaQuery.js
Module parse failed: The keyword 'interface' is reserved (5:0)
```

**Comment by pnkapadia6** [comment]
@wcandillon 
Same here. It isn't transpiled to es5 and gives error while compiling. I'm trying to use it alongwith https://github.com/necolas/react-native-web

**Comment by gangwarily** [comment]
> @wcandillon
> Same here. It isn't transpiled to es5 and gives error while compiling. I'm trying to use it alongwith https://github.com/necolas/react-native-web

@pnkapadia6, in your case, you will have to configure Webpack to compile specific directories in node_modules to be able to use libraries with RNW. I ran into this same issue and had to drop the parcel bundler as it seems you can't configure babel to transpile dependencies in node_modules :/

**Comment by wcandillon** [comment]
This is fixed now 👍 However this new version is non backward compatible.
