### ISSUE TITLE
Error for ResponsiveComponent in iOS and Android

### ISSUE THREAD

**Issue by cjadhav** [wcandillon/react-native-responsive-ui#46]
Hi,

I am using following method to use this module.
```
import { ResponsiveComponent, ResponsiveStyleSheet } from "react-native-responsive-ui";

class MyComponent extends ResponsiveComponent {
render(){
    return (
        <View>
          ...
        </View>
     )
    }
get respStyles() {
    return ResponsiveStyleSheet.select([
      {
        query: { orientation: "portrait" },
        style: {
          container: {
            flex: 1,
            flexDirection: "column"
          }
        }
      },
      {
        query: { orientation: "landscape" },
        style: {
          container: {
            flex: 1,
            flexDirection: "row"
          }
        }
      }
    ]);
  }
}

export default MyComponent;
```

I have updated all modules to latest including React-Native 0.59.9
and i started facing weird runtime error as
`Super expression must either be null or a function`

and this for all component which are using `ResponsiveComponent`.

You help is highly appreciable.

**Comment by wcandillon** [comment]
Hello @cjadhav,

Unfortunately, ResponsiveComponent has been deprecated. Could you update to the latest API? Sorry for the trouble.

**Comment by cjadhav** [comment]
Thanks @wcandillon for quick reply.
I'll update the source with latest methods.
You can close the issue as per your connivence.

**Comment by cjadhav** [comment]
Hi @wcandillon,
I am facing new error. I have done the change for latest update.
using the `useStylesheet` now my look like this,
```
import { useStylesheet } from "react-native-responsive-ui";

class MyComponent extends Component {
render(){
    const respStyles = useStylesheet(staticStyle);
    return (
        <View style={respStyles.container}>
          ...
        </View>
     )
    }
}

const staticStyle = [
  {
    query: { orientation: "portrait" },
    style: {
      container: {
        flex: 1,
        flexDirection: "column"
      }
    }
  },
  {
    query: { orientation: "landscape" },
    style: {
      container: {
        flex: 1,
        flexDirection: "row"
      }
    }
  }
];

export default MyComponent;

```


Whenever this component is called to render app crashes with following error,
`Invariant Violation: Invariant Violation: Invariant Violation: Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)`

Can you help to solve this ?

Thanks

**Comment by wcandillon** [comment]
Sorry about that! Yes let me provide an update that is friendly for class components 😅

**Comment by cjadhav** [comment]
Hi @wcandillon,

Thanks for the fix but it's still broken for me.
Giving same error for v.2.1.0 also.

![Simulator Screen Shot - iPhone Xʀ - 2019-06-20 at 19 06 56](https://user-images.githubusercontent.com/6572823/59853508-a38bd480-938e-11e9-84ec-c38bf647162e.png)

Tested on iPhone XR (iOS 12.2)

Please help me.

**Comment by wcandillon** [comment]
Sorry I should have been clearer. You can use ResponsiveComponent again. Please refer to the documentation athttps://github.com/wcandillon/react-native-responsive-ui/blob/master/README.md

**Comment by cjadhav** [comment]
Thanks @wcandillon.

Using `ResponsiveComponent` to create class. But not sure how should I call `getStyleSheet` to receive orientation based styles.

```
import { ResponsiveComponent, getStyleSheet } from "react-native-responsive-ui";

class MyComponent extends ResponsiveComponent {
render(){
    const respStyles = getStyleSheet(staticStyle);
    return (
        <View style={respStyles.container}>
          ...
        </View>
     )
    }
}

const staticStyle = [
  {
    query: { orientation: "portrait" },
    style: {
      container: {
        flex: 1,
        flexDirection: "column"
      }
    }
  },
  {
    query: { orientation: "landscape" },
    style: {
      container: {
        flex: 1,
        flexDirection: "row"
      }
    }
  }
];

export default MyComponent;
```

I am facing errors in this.
and not getting how to use query based stylesheet.

**Comment by cjadhav** [comment]
@wcandillon, I have tried `useStylesheet` as per documentation but gives hook error.
tried `getStyleSheet ` but bot getting how to pass static styles to that function.

Your help is highly appreciable.

**Comment by wcandillon** [comment]
@cjadhav can you try with `getStyleSheet` as

```tsx
    const {width, height} = this.state;
    const respStyles = getStyleSheet({width, height}, staticStyle);
```

**Comment by cjadhav** [comment]
@wcandillon, sorry but above solution also failed.
It's giving me TypeError.

`TypeError: (0 , _reactNativeResponsiveUi.getStyleSheet) is not a function`

**Comment by wcandillon** [comment]
@cjadhav could it be an issue with the cache of your package bundle?

**Comment by cjadhav** [comment]
@wcandillon Tried with all cache clear/reset.
No luck. Giving same error.
<img width="412" alt="Screenshot 2019-06-20 at 10 56 40 PM" src="https://user-images.githubusercontent.com/6572823/59868516-b1515200-93ae-11e9-999c-e10dfaa2b670.png">

Taking the height and width from `Dimensions.get("window")`

**Comment by cjadhav** [comment]
Same error with V.2.1.1 from your latest module.

**Comment by wcandillon** [comment]
sorry to hear that, can you send me the exact code snippet?

**Comment by cjadhav** [comment]
@wcandillon, Sure.
This is code just removed the other business login.

```
import React, { Component } from "react";
import { StyleSheet, Text, View, Image, Platform, Animated, TextInput, ScrollView } from "react-native";
import { Dimensions, ImageBackground, TouchableOpacity, TouchableHighlight } from "react-native";
import { ResponsiveComponent, getStyleSheet } from "react-native-responsive-ui";

class Schedules extends ResponsiveComponent {
  constructor(props) {
    super(props);
    this.state = {
      height: Dimensions.get("window").height,
      width: Dimensions.get("window").width
    };
  }

  render() {
    // const { respStyles } = this;
    const { width, height } = this.state;
    const respStyles = getStyleSheet({ width, height }, staticStyle);

    return (
      <View
        style={styles.viewContainer}
        onLayout={e => this.setState({ width: e.nativeEvent.layout.width, height: e.nativeEvent.layout.height })}
      >
        <View style={respStyles.viewHolder} />
      </View>
    );
  }
}

const staticStyle = [
  {
    query: { orientation: "portrait" },
    style: {
      viewHolder: {
        flex: 1,
        flexDirection: "column"
      }
    }
  },
  {
    query: { orientation: "landscape" },
    style: {
      viewHolder: {
        flex: 1,
        flexDirection: "row"
      }
    }
  }
];

const styles = StyleSheet.create({
  viewContainer: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#F0F0F0"
  }
});

export default Schedules;

```

**Comment by wcandillon** [comment]
haha thks and sorry ;-) It's getStylesheet not getStyleSheet 🙈

**Comment by cjadhav** [comment]
@wcandillon, It worked.
Thank you so much for the help.
