### ISSUE TITLE
MediaQuery dimensions?

### ISSUE THREAD

**Issue by maartenvandillen** [wcandillon/react-native-responsive-ui#55]
Hi I got a question about the min/max width/height props of the MediaQuery component. What values should I put in there? Is there an overview of common screen sizes to determine a small vs a big screen in the same orientation? I'm currently working with a value of 350 (width) but that's just something I made up.

E.g. iPhone X has a screen width of 375, iPhone 5s has a screen width of 320.

**Comment by crutchcorn** [comment]
This is highly contextual and depends primarily on your design decisions. What I tend to do in my application is work with my designer to have a list of breakpoints that we use across our mockups and codebase to keep consistent.

It's a good question overall, but one that exceeds the scope of GitHub issues IMO and as such I am closing this issue

Maybe this might be a good starting point resource?

https://www.browserstack.com/guide/responsive-design-breakpoints
