### ISSUE TITLE
When I use typescript to develop, always met error by calling useDemission.

### ISSUE THREAD

**Issue by yafeya** [wcandillon/react-native-responsive-ui#56]
When I use typescript to develop, always met error by calling useDemission. Always said, cannot call the hook in the body.

So, is there any suggestion to use this util under typescript?

**Comment by wcandillon** [comment]
I think that it simply means that you cannot use this hook within a class component.

**Comment by yafeya** [comment]
I encountered 2 scenario which I got trouble, would like to get help from your side.
1. When I import "MediaQuery" component to a typescript component, I met a issue.
![image](https://user-images.githubusercontent.com/11024917/61024839-7789cf00-a3e1-11e9-978a-88d9ec3e9ce8.png)
2. I take a look at the code, found the "MediaQuery" is exported from "dist", so when i change the code to below. I met another issue.
![image](https://user-images.githubusercontent.com/11024917/61024912-a0aa5f80-a3e1-11e9-870f-5730883067a7.png)

![image](https://user-images.githubusercontent.com/11024917/61024939-ad2eb800-a3e1-11e9-80c6-40889e04edc7.png)

**Comment by yafeya** [comment]
I think maybe I got some mistake configuration. So, maybe you can provide some help. :)

**Comment by yafeya** [comment]
@wcandillon 1 update, for the 1st issue, when I use @ts.ignore, the "tsc" command will pass. And I can run the feature with your plugin. Will update you when I have new feature requirement. :)

**Comment by tafelito** [comment]
I think this still an issue. TS complains about not finding `'react-native-responsive-ui'`
