### ISSUE TITLE
TypeError: TypeError: (0, _reactNativeResponsiveUi.getStyleSheet) is not a function. 

### ISSUE THREAD

**Issue by alex4dev** [wcandillon/react-native-responsive-ui#58]
Hello, 
I have a problem with the getStyleSheet function, like in the example i try to get my styles from the render function.

like this :
`  public render(): any {
    const dims = Dimensions.get('window');
    const rStyles = getStyleSheet(
      { width: dims.width, height: dims.height },
      responsiveStyles
    );
}
`

and responsive styles :
`
const responsiveStyles = [
  {
    query: { orientation: 'landscape' },
    style: {
      mainContainer: {
        flexDirection: 'row'
      },
      topContainer: {
        flex: 1
      }
    }
  },
  {
    query: { orientation: 'portrait' },
    style: {
      mainContainer: {
        flexDirection: 'column'
      },
      topContainer: {
        flex: 0
      }
    }
  }
`

here the full error log : 
`TypeError: TypeError: (0, _reactNativeResponsiveUi.getStyleSheet) is not a function. (In '(0, _reactNativeResponsiveUi.getStyleSheet)({ width: dims.width, height: dims.height }, _LivestageStyles.responsiveStyles)', '(0, _reactNativeResponsiveUi.getStyleSheet)' is undefined) This error is located at: in LoginContainer (created by Connect(LoginContainer)) in Connect(LoginContainer) `

I use react 16.8.3 react native 0.59.10 typescript 2.9.2 and responvive-ui 2.1.1
Anybody know if i have missed something?

Thanks

**Comment by projetsdiy** [comment]
Same problem with react 0.60.5. Did you found a solution ?

**Comment by yl-flyer** [comment]
like @projetsdiy says, you must replace 'getStyleSheet' by 'getStylesheet', sheet is lowercase.
I found the mistake in documentation, It must be corrected.

`
import React from "react";
import {ResponsiveComponent, getStylesheet} from "react-native-responsive-ui";

export default class Debug extends ResponsiveComponent {
    render() {
        const {width, height} = this.state.window;
        const styles = [
            {
                query: { minHeight: 500 },
                style: { container: { backgroundColor: "red" } }
            }
        ];
        const style = getStylesheet({width, height}, styles)
        return <View style={style.container} />
    }
}
`
