### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by philpettican** [wcandillon/react-native-responsive-ui#63]
Hi,

I'm currently using react-native-responsive-ui@2.1.1 with react-native@0.61.2 and I'm getting the following warning:

![componentWillMount has been renamed](https://user-images.githubusercontent.com/15366459/66771145-5984ac80-eeb1-11e9-945e-a41957ad2dbf.png)

ImageCarousel extends ResponsiveComponent.

**Comment by crutchcorn** [comment]
Fixed as-of 2.1.5
