### ISSUE TITLE
No matching version found. Unable to install react-native-responsive-ui > 2.0.0

### ISSUE THREAD

**Issue by Manthravadi** [wcandillon/react-native-responsive-ui#66]
Hi All,

I am trying to update my dependencies and found that react-native-responsive-ui shows latest version as 2.1.1 on npmjs as well as github. 

However, when I run npm i -S react-native-responsive-ui@latest, it always installs version 1.1.1 which is pretty old. Even if I try npm i -S react-native-responsive-ui@2.1.1 or 2.1.0 or 2.0.0, it always installs 1.1.1. I think there might be an issue with publishing these versions. Any help here would be highly appreciated. 

We can see the failure here when we try to run it too: [RunKit](https://npm.runkit.com/react-native-responsive-ui)

Here is a screenshot of the npm install error I see:

![image](https://user-images.githubusercontent.com/4766825/80812446-a037bb00-8be5-11ea-9d09-3980a4430d90.png)

~ Manthravadi

**Comment by Manthravadi** [comment]
bumping ...

**Comment by crutchcorn** [comment]
This no longer appears to be happening. We just published `2.1.2`, so that may have fixed things. Please let me know if this continues to occur in the future
